import { dlopen, FFIType } from "bun:ffi";
import { cuaCall } from "../src/driver/cli";
const u32 = dlopen("user32.dll", { GetForegroundWindow: { returns: FFIType.ptr, args: [] } });
const fg = () => String(u32.symbols.GetForegroundWindow());
const t0 = performance.now();
const p = Bun.spawn(["powershell", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", "native/win/highlight.ps1"], { stdin: "pipe", stdout: "pipe", stderr: "pipe" });
const reader = p.stdout.getReader();
const first = new TextDecoder().decode((await reader.read()).value);
console.log("helper:", first.trim(), Math.round(performance.now() - t0), "ms to start");
const before = fg();
p.stdin.write(JSON.stringify({ x: 860, y: 440, w: 200, h: 120, ms: 2500 }) + "\n"); p.stdin.flush();
await Bun.sleep(600);
const during = fg();
await cuaCall("start_session", { session: "Blue-9" });
const lw = (await cuaCall("list_windows", { session: "Blue-9" })).data.windows;
const ring = lw.find((w: any) => w.title === "agent-highlight");
const top = lw.filter((w: any) => w.title && !w.minimized).sort((a: any, b: any) => b.z_index - a.z_index)[0];
console.log("ring window:", ring ? JSON.stringify(ring.bounds) : "not found", "| topmost:", top?.title);
console.log("foreground unchanged while showing:", before === during);
await Bun.sleep(2600);
const lw2 = (await cuaCall("list_windows", { session: "Blue-9" })).data.windows;
console.log("ring gone after fade:", !lw2.some((w: any) => w.title === "agent-highlight"), "| foreground still unchanged:", fg() === before);
p.stdin.end();
const code = await Promise.race([p.exited, Bun.sleep(4000).then(() => "still running")]);
console.log("helper exit on stdin close:", code);
const err = await new Response(p.stderr).text(); if (err.trim()) console.log("stderr:", err.slice(0, 600));
